black:
  max:
  - 30
  - 150
  - 255
  min:
  - 0
  - 0
  - 0
blue:
  max:
  - 255
  - 140
  - 110
  min:
  - 0
  - 0
  - 0
green:
  max:
  - 255
  - 100
  - 255
  min:
  - 47
  - 0
  - 135
red:
  max:
  - 255
  - 255
  - 255
  min:
  - 1
  - 160
  - 100
violet:
  max:
  - 130
  - 255
  - 100
  min:
  - 0
  - 150
  - 0
white:
  max:
  - 255
  - 255
  - 255
  min:
  - 190
  - 115
  - 0
